import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { unstable_cache } from "next/cache";

// Typed access to data/sources/registry.json — the generated record of every
// source the datasets cite. Generated by app/build-sources.mjs; see
// data/sources/curated.json for the curation that feeds it.
//
// Read from disk rather than the database on purpose. Provenance is a property
// of the committed dataset, not of whatever happens to be loaded into Neon, and
// it should stay readable even if the database is unreachable.

export type Reliability = "primary" | "secondary" | "tertiary";
export type Verification = "full-text" | "metadata-only" | "unverified";

export interface Source {
  id: string | null;
  url: string;
  host: string;
  title: string | null;
  publisher: string;
  authors: string[] | null;
  year: number | null;
  kind: string;
  reliability: Reliability;
  verification: Verification;
  deepLink: boolean;
  supports: string | null;
  doesNotSupport: string | null;
  accessed: string | null;
  note: string | null;
  citations: number;
  numericCitations: number;
  usedIn: string[];
  exampleRecords: string[];
}

/**
 * A curated document that no dataset cites. Same fields as a Source minus the
 * usage counts, because there is no usage. These are kept and displayed on
 * purpose: a source that was read and rejected, or a conflicting figure that
 * was deliberately not merged, is part of the provenance record, and dropping
 * it would quietly erase the reasoning. See `background` in build-sources.mjs.
 */
export type BackgroundDocument = Omit<
  Source,
  "note" | "citations" | "numericCitations" | "usedIn" | "exampleRecords"
>;

export interface SourceRegistry {
  reliabilityRules: Record<Reliability, string>;
  citationRules: Record<string, string>;
  totals: {
    distinctSources: number;
    backgroundDocuments: number;
    citations: number;
    numericCitations: number;
    numericOnShallowLink: number;
    numericOnTertiary: number;
    fullTextVerified: number;
    backgroundFullTextVerified: number;
    byReliability: Partial<Record<Reliability, number>>;
  };
  sources: Source[];
  /** Absent in registries generated before background documents were tracked. */
  background?: BackgroundDocument[];
}

export const getSourceRegistry = unstable_cache(
  async (): Promise<SourceRegistry | null> => {
    try {
      const raw = await readFile(join(process.cwd(), "..", "data", "sources", "registry.json"), "utf8");
      return JSON.parse(raw) as SourceRegistry;
    } catch {
      // The page degrades to an explanation rather than a crash.
      return null;
    }
  },
  ["source-registry-v1"],
  { revalidate: 3600 }
);

export const RELIABILITY_LABEL: Record<Reliability, string> = {
  primary: "Primary",
  secondary: "Secondary",
  tertiary: "Tertiary",
};

// Human names for the `kind` discriminator, which is finer-grained than the
// reliability tier and is what actually tells you what you're looking at.
export const KIND_LABEL: Record<string, string> = {
  "vendor-tds": "Manufacturer technical data sheet",
  "vendor-datasheet": "Manufacturer datasheet",
  "vendor-handbook": "Distributor handbook",
  "peer-reviewed": "Peer-reviewed literature",
  "preprint-mirror": "Author copy of a published paper",
  regulation: "Statute or regulation",
  "standards-body": "Standards body",
  "standards-reseller": "Standards reseller",
  "government-database": "Government database",
  "government-report": "Government report",
  "nutrition-label": "Nutrition labelling",
  "guideline-publisher": "Style-guideline publisher",
  "club-guide": "Homebrew club guide",
  "trade-association": "Trade association",
  "extension-service": "University extension service",
  "practitioner-tool": "Practitioner reference tool",
  "document-host": "Document host",
  encyclopedia: "Encyclopedia",
  "trade-publication": "Brewing trade publication",
  "enthusiast-blog": "Enthusiast blog",
  "author-site": "Author's own site",
  book: "Book",
  "book-publisher": "Book publisher",
};

export function kindLabel(kind: string): string {
  return KIND_LABEL[kind] ?? kind;
}

/** Cite a source the way a bibliography would, from whatever fields exist. */
export function formatCitation(s: Source | BackgroundDocument): string {
  const bits: string[] = [];
  if (s.authors?.length) {
    bits.push(s.authors.length > 3 ? `${s.authors[0]} et al.` : s.authors.join(", "));
  }
  if (s.year) bits.push(`(${s.year})`);
  if (s.title) bits.push(s.title);
  if (s.publisher && s.publisher !== s.title) bits.push(s.publisher);
  return bits.length ? bits.join(". ") : s.url;
}

/** Sources grouped by reliability, each group ordered by how much rests on it. */
export function groupByReliability(sources: Source[]): { tier: Reliability; sources: Source[] }[] {
  const order: Reliability[] = ["primary", "secondary", "tertiary"];
  return order
    .map((tier) => ({
      tier,
      sources: sources.filter((s) => s.reliability === tier).sort((a, b) => b.citations - a.citations),
    }))
    .filter((g) => g.sources.length > 0);
}

/**
 * The citations this project itself considers weak: a number resting on a
 * publisher's homepage rather than on the document the number came from.
 * Surfaced rather than hidden — see /sources.
 */
export function weakNumericCitations(sources: Source[]): Source[] {
  return sources
    .filter((s) => s.numericCitations > 0 && !s.deepLink)
    .sort((a, b) => b.numericCitations - a.numericCitations);
}
