import { NextResponse } from "next/server";
import { findStyle } from "@/lib/guidelines";
import { getFermentableCatalog, getHopCatalog } from "@/lib/ingredients-curated";
import { buildRecipeSkeleton } from "@/lib/recipe-builder";
import { toBeerXml, xmlFilename, type XmlRecipe } from "@/lib/beerxml";

export const dynamic = "force-dynamic";

// GET /guidelines/<edition>/<code>/beerxml[?gal=5|?litres=20]
// Exports the auto-generated starting recipe for a style as BeerXML, so you
// can open a guideline straight in BeerSmith/Brewfather and start tweaking.
export async function GET(
  request: Request,
  { params }: { params: Promise<{ edition: string; code: string }> }
) {
  const { edition, code } = await params;
  const style = await findStyle(edition, code);
  if (!style) return new NextResponse("Style not found", { status: 404 });

  const url = new URL(request.url);
  const wantGal = parseFloat(url.searchParams.get("gal") ?? "");
  const wantL = parseFloat(url.searchParams.get("litres") ?? url.searchParams.get("liters") ?? "");
  const batchSizeGal = Number.isFinite(wantGal) && wantGal > 0
    ? wantGal
    : Number.isFinite(wantL) && wantL > 0
      ? wantL / 3.785411784
      : 5;

  const [fermCat, hopCat] = await Promise.all([getFermentableCatalog(), getHopCatalog()]);
  const skeleton = buildRecipeSkeleton(
    {
      name: style.name,
      categoryName: style.category.name,
      ogMin: style.ogMin, ogMax: style.ogMax, fgMin: style.fgMin, fgMax: style.fgMax,
      ibuMin: style.ibuMin, ibuMax: style.ibuMax, srmMin: style.srmMin, srmMax: style.srmMax,
      abvMin: style.abvMin, abvMax: style.abvMax,
    },
    fermCat.map((f) => ({ id: f.id, name: f.name, ppg: f.ppg, colorLovibond: f.colorLovibond, type: f.type, requiresConversion: f.requiresConversion })),
    hopCat.map((h) => ({ id: h.id, name: h.name, alphaMin: h.alphaMin, alphaMax: h.alphaMax, purpose: h.purpose, styleTags: h.styleTags, country: h.country })),
    { batchSizeGal }
  );

  if (!skeleton.buildable) {
    return new NextResponse(
      `Cannot generate a recipe for this style: ${skeleton.reason ?? "insufficient published targets"}`,
      { status: 422 }
    );
  }

  const out: XmlRecipe = {
    name: `${style.name} (WortHogg starting recipe)`,
    brewer: "WortHogg",
    styleName: style.name,
    batchSizeGal: skeleton.batchSizeGal,
    boilTimeMin: 60,
    efficiencyPct: skeleton.efficiencyPct,
    og: skeleton.computed.og,
    fg: skeleton.computed.fg,
    ibu: skeleton.computed.ibu,
    colorSrm: skeleton.computed.srm,
    abv: skeleton.computed.abv,
    notes:
      `Auto-generated by WortHogg from the published targets for ${style.name} ` +
      `(${style.category.edition.title}). A ${skeleton.family} skeleton at ` +
      `${skeleton.efficiencyPct}% efficiency — a starting point to adjust, not a finished recipe.`,
    fermentables: skeleton.fermentables.map((f) => ({
      name: f.name,
      amountLb: f.amountLb,
      ppg: f.ppg,
      colorLovibond: f.colorLovibond,
      type: f.isGrain ? "Grain" : "Sugar",
    })),
    hops: skeleton.hops.map((h) => ({
      name: h.name,
      amountOz: h.amountOz,
      alphaPct: h.alphaPct,
      timeMin: h.timeMin,
      use: "Boil",
    })),
    yeasts: [],
  };

  return new NextResponse(toBeerXml(out), {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Content-Disposition": `attachment; filename="${xmlFilename(out.name)}"`,
    },
  });
}
